theme: jekyll-theme-dinky
title: Marcos Rivera-Almazo blog
description: Hello everyone! Im a Computational Chemistry student (currently pursuing my PhD) 
at Universidad Autónoma Metropolitana - Iztapalapa, in Mexico. 
