theme: jekyll-theme-dinky
title: Marcos Rivera-Almazo's blog
description: Hello everyone! I'm a Computational Chemistry student (currently pursuing my PhD) 
at Universidad Autónoma Metropolitana - Iztapalapa, in Mexico. 
